export const SystemErrors = {
  EBLOCKED: 'EBLOCKED',
  ETIMEOUT: 'ETIMEOUT',
  EINVAL: 'EINVAL',
  ENODATA: 'ENODATA',
  EBADREDIRECT: 'EBADREDIRECT',
  EUNSUPPORTEDPROTOCOL: 'EUNSUPPORTEDPROTOCOL',
  FETCH_ERROR: 'FETCH_ERROR',
  ABORTED: 'ABORTED',
  QUEUE_FULL: 'queue_full',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;
